;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

+GameplayTagList=(Tag="Feedback.Ball.Impact",DevComment="")
+GameplayTagList=(Tag="Feedback.Ball.LandedInWater",DevComment="")
+GameplayTagList=(Tag="Feedback.Ball.LandedInHole",DevComment="")
+GameplayTagList=(Tag="Feedback.Ball.Impact",DevComment="")
+GameplayTagList=(Tag="Feedback.Ball.Rolling",DevComment="")

+GameplayTagList=(Tag="Feedback.Putter.HitBall",DevComment="")

+GameplayTagList=(Tag="Feedback.Session.TurnStarted",DevComment="")
+GameplayTagList=(Tag="Feedback.Session.PlayerJoined",DevComment="")
+GameplayTagList=(Tag="Feedback.Session.PlayerDisconnected",DevComment="")

+GameplayTagList=(Tag="Feedback.UI.Score.HoleInOne",DevComment="in 1 BABY!!")
+GameplayTagList=(Tag="Feedback.UI.Score.Albatross",DevComment="-3")
+GameplayTagList=(Tag="Feedback.UI.Score.Eagle",DevComment="-2")
+GameplayTagList=(Tag="Feedback.UI.Score.Birdie",DevComment="-1")
+GameplayTagList=(Tag="Feedback.UI.Score.Par",DevComment="0")
+GameplayTagList=(Tag="Feedback.UI.Score.Boggie",DevComment="+1")




+GameplayTagList=(Tag="ISM.Possession.Default",DevComment="")
+GameplayTagList=(Tag="ISM.State.Collected",DevComment="")
+GameplayTagList=(Tag="ISM.State.Converted",DevComment="")
+GameplayTagList=(Tag="ISM.State.Converting",DevComment="")
+GameplayTagList=(Tag="ISM.State.Damaged",DevComment="")
+GameplayTagList=(Tag="ISM.State.Destroyed",DevComment="")
+GameplayTagList=(Tag="ISM.State.Hidden",DevComment="")
+GameplayTagList=(Tag="ISM.State.Intact",DevComment="")
+GameplayTagList=(Tag="ISM.State.Selected",DevComment="")
+GameplayTagList=(Tag="ISM.Type.Rock",DevComment="")
+GameplayTagList=(Tag="ISM.Type.Vegetation.Tree",DevComment="")




